site_name: Documentation Site Name
theme:
  name: material
  # palette:
  #   primary: teal
  features: 
    - content.code.annotate
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top

repo_url: https://github.com/caskeychr/mkdocs-template

# edit_uri: blob/develop/docs/

extra_css:
  - css/extra.css

markdown_extensions:
  - admonition
  - abbr
  - footnotes
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.superfences
  # - toc:
  #     permalink: "#"
  - pymdownx.snippets:
      base_path: "docs"
  - pymdownx.betterem:
      smart_enable: all

# Page Tree
nav:
  - Home: 'index.md'
  - Tutorials:
    - 'tutorials/overview.md'
    - 'tutorials/guide1/guide1.md'
    - 'tutorials/guide2/guide2.md'
  - How-To Guides: 
    - 'how-to/overview.md'
    - 'how-to/how-to1/how-to1.md'
    - 'how-to/how-to2/how-to2.md'
  - Reference:
    - 'reference/overview.md'
    - Section 1:
      - 'reference/section-one/article1.md'
      - 'reference/section-one/article2.md'
    - Section 2:
      - 'reference/section-two/article3.md'
      - 'reference/section-two/article4.md'
  - Concepts:
    - 'concepts/overview.md'
    - Section 1:
      - 'concepts/section-one/article1.md'
      - 'concepts/section-one/article2.md'
    - Section 2:
      - 'concepts/section-two/article3.md'
      - 'concepts/section-two/article4.md'